[package]
name = "fluent-ergonomics"
version = "0.1.0"
authors = ["savanni"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent = "0.11"
unic-langid = "0.8"
fluent-syntax = "*"
